# Yelp Topic Modeling: BERTopic vs. FASTopic


1. Use a pretrained SentenceTransformer to create review embeddings.
2. Fit **one global BERTopic model** and **one global FASTopic model** on a
   representative California review sample.
3. Compare the models using:
   - C_v coherence
   - NPMI coherence
   - U_Mass coherence
   - Topic diversity
   - Runtime
4. Save both fitted models.
5. Use the selected model to assign topics to all reviews.
6. Export the top topics for every business for use in the Shiny dashboard.

The transformer is used for pretrained embedding inference. BERTopic and
FASTopic still need an unsupervised fit on the Yelp corpus so that the topics
are relevant to Yelp reviews. No hand-labeled topic data is required.

In [ ]:
# Use the PyTorch version already provided by Colab.
# Do not uninstall/reinstall torch or force a CUDA wheel.
!pip -q install -U bertopic fastopic topmost sentence-transformers gensim umap-learn hdbscan pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.7/596.7 kB 32.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 129.5 MB/s eta 0:00:00

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

## 1. Configuration

In [ ]:
from pathlib import Path

DATA_PATH = Path("/content/drive/MyDrive/yelp_reviews_clean_CA.csv")
BUSINESS_PATH = Path(
    "/content/drive/MyDrive/yelp_academic_dataset_business.csv"
)

OUTPUT_DIR = Path("/content/drive/MyDrive/yelp_topic_modeling")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
SEED = 42
N_TOPICS = 25
TOP_N_WORDS = 10

# Run a small test first. Change to False for the final comparison.
TEST_MODE = True

if TEST_MODE:
    MAX_DOCS_FOR_FIT = 5_000
    MAX_REVIEWS_PER_BUSINESS_FOR_FIT = 10
    FASTOPIC_EPOCHS = 10
else:
    MAX_DOCS_FOR_FIT = 50_000
    MAX_REVIEWS_PER_BUSINESS_FOR_FIT = 30
    FASTOPIC_EPOCHS = 50

# Metrics can be expensive on very large corpora.
MAX_DOCS_FOR_COHERENCE = 20_000

# Full-data topic assignment is intentionally disabled during initial testing.
RUN_FULL_DATA_INFERENCE = True

# Select the model after reviewing the comparison table:
# "BERTopic" or "FASTopic"
SELECTED_MODEL_FOR_EXPORT = "BERTopic"

INFERENCE_BATCH_SIZE = 2_000
EMBEDDING_BATCH_SIZE = 128

if not DATA_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found: {DATA_PATH}\n"
        "Upload yelp_reviews_clean_CA.csv to MyDrive or update DATA_PATH."
    )

print(f"Test mode:       {TEST_MODE}")
print(f"Fit documents:   up to {MAX_DOCS_FOR_FIT:,}")
print(f"Number of topics:{N_TOPICS}")
print(f"Output directory:{OUTPUT_DIR}")

Test mode:       True
Fit documents:   up to 5,000
Number of topics:25
Output directory:/content/drive/MyDrive/yelp_topic_modeling

## 2. Imports, device, and reproducibility

In [ ]:
import gc
import json
import random
import time
import warnings

import numpy as np
import pandas as pd
import polars as pl
import torch

from bertopic import BERTopic
from fastopic import FASTopic
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel
from hdbscan import HDBSCAN
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from topmost.preprocess import Preprocess
from umap import UMAP

warnings.filterwarnings("ignore")

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)
    DEVICE = "cuda"
else:
    DEVICE = "cpu"

print(f"PyTorch: {torch.__version__}")
print(f"Device:  {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU:     {torch.cuda.get_device_name(0)}")

PyTorch: 2.11.0+cu128
Device:  cuda
GPU:     Tesla T4

## 3. Load and standardize the Yelp data

In [ ]:
reviews_lazy = pl.scan_csv(
    DATA_PATH,
    infer_schema_length=20_000,
    ignore_errors=True,
)

available_columns = reviews_lazy.collect_schema().names()
print("Available columns:")
print(available_columns)


def first_existing(candidates, available, required=False):
    match = next(
        (column for column in candidates if column in available),
        None,
    )
    if required and match is None:
        raise KeyError(
            f"None of the required columns {candidates} were found. "
            f"Available columns: {available}"
        )
    return match


TEXT_COL = first_existing(
    ["text", "review_text", "review"],
    available_columns,
    required=True,
)
BUSINESS_ID_COL = first_existing(
    ["business_id"],
    available_columns,
    required=True,
)
BUSINESS_NAME_COL = first_existing(
    ["business_name", "name"],
    available_columns,
)
DATE_COL = first_existing(
    ["date", "review_date"],
    available_columns,
)

selected_columns = [BUSINESS_ID_COL, TEXT_COL]
if BUSINESS_NAME_COL is not None:
    selected_columns.append(BUSINESS_NAME_COL)
if DATE_COL is not None:
    selected_columns.append(DATE_COL)

reviews_df = (
    reviews_lazy
    .select(selected_columns)
    .filter(pl.col(BUSINESS_ID_COL).is_not_null())
    .filter(pl.col(TEXT_COL).is_not_null())
    .with_columns(
        pl.col(BUSINESS_ID_COL).cast(pl.Utf8),
        pl.col(TEXT_COL).cast(pl.Utf8).str.strip_chars(),
    )
    .filter(pl.col(TEXT_COL).str.len_chars() >= 20)
    .unique(subset=[BUSINESS_ID_COL, TEXT_COL])
    .collect()
)

if BUSINESS_NAME_COL is None:
    if not BUSINESS_PATH.exists():
        raise FileNotFoundError(
            "The review CSV does not contain a business-name column, and "
            f"the business file was not found at {BUSINESS_PATH}."
        )

    business_df = (
        pl.read_csv(
            BUSINESS_PATH,
            columns=["business_id", "name"],
            infer_schema_length=10_000,
            ignore_errors=True,
        )
        .with_columns(
            pl.col("business_id").cast(pl.Utf8),
            pl.col("name").cast(pl.Utf8).str.strip_chars(),
        )
        .unique(subset=["business_id"])
        .rename({"name": "business_name"})
    )

    reviews_df = reviews_df.join(
        business_df,
        left_on=BUSINESS_ID_COL,
        right_on="business_id",
        how="left",
    )
    BUSINESS_NAME_COL = "business_name"

reviews_df = (
    reviews_df
    .with_columns(
        pl.col(BUSINESS_NAME_COL)
        .cast(pl.Utf8)
        .fill_null("Unknown business")
        .str.strip_chars()
    )
)

print(f"Clean review rows:  {reviews_df.height:,}")
print(
    "Unique businesses: "
    f"{reviews_df.get_column(BUSINESS_ID_COL).n_unique():,}"
)
reviews_df.head()

Available columns:
['review_id', 'user_id', 'business_id', 'business_name', 'stars', 'sentiment', 'date', 'text']
Clean review rows:  346,772
Unique businesses: 5,203

shape: (5, 4)
┌────────────────────────┬─────────────────────────────────┬──────────────────────────┬────────────┐
│ business_id            ┆ text                            ┆ business_name            ┆ date       │
│ ---                    ┆ ---                             ┆ ---                      ┆ ---        │
│ str                    ┆ str                             ┆ str                      ┆ str        │
╞════════════════════════╪═════════════════════════════════╪══════════════════════════╪════════════╡
│ U897DhJaaa3qyr1PVjxfWQ ┆ I had the brisket melt for $10… ┆ Georgia's Smokehouse     ┆ 2015-02-11 │
│ fVUurZgbWXzp2QzDzJzmpA ┆ I like their food, but as of l… ┆ Pickles & Swiss          ┆ 2021-03-05 │
│ SZU9c8V2GuREDN5KgyHFJw ┆ Foods are good and nasty, serv… ┆ Santa Barbara Shellfish  ┆ 2021-11-22 │
│                        ┆                                 ┆ Compan…                  ┆            │
│ 6JFTijOMHB46yBoyVOjPCA ┆ Definitely the most beautiful … ┆ Santa Barbara County     ┆ 2014-05-17 │
│                        ┆                                 ┆ Courthous…               ┆            │
│ _swrAjNgk60HIGLVzHiqmA ┆ My favorite Santa Barbara Thai… ┆ Khao Kaeng by Empty Bowl ┆ 2018-11-08 │
│                        ┆                                 ┆ Gourm…                   ┆            │
└────────────────────────┴─────────────────────────────────┴──────────────────────────┴────────────┘

## 4. Create a business-balanced fitting sample

A simple random sample can be dominated by chains and businesses with many
reviews. This sample first caps the reviews contributed by each business and
then applies a global cap.

In [ ]:
shuffled_df = reviews_df.sample(
    fraction=1.0,
    shuffle=True,
    seed=SEED,
)

fit_df = (
    shuffled_df
    .group_by(BUSINESS_ID_COL, maintain_order=True)
    .head(MAX_REVIEWS_PER_BUSINESS_FOR_FIT)
)

if fit_df.height > MAX_DOCS_FOR_FIT:
    fit_df = fit_df.sample(
        n=MAX_DOCS_FOR_FIT,
        shuffle=True,
        seed=SEED,
    )

fit_docs = fit_df.get_column(TEXT_COL).to_list()

print(f"Documents used for fitting: {len(fit_docs):,}")
print(
    "Businesses represented:      "
    f"{fit_df.get_column(BUSINESS_ID_COL).n_unique():,}"
)
print(
    "Average reviews per business:"
    f" {len(fit_docs) / fit_df.get_column(BUSINESS_ID_COL).n_unique():.2f}"
)

Documents used for fitting: 5,000
Businesses represented:      3,270
Average reviews per business: 1.53

## 5. Load the pretrained embedding model

In [ ]:
embedding_model = SentenceTransformer(
    EMBEDDING_MODEL_NAME,
    device=DEVICE,
)

embedding_start = time.perf_counter()

fit_embeddings = embedding_model.encode(
    fit_docs,
    batch_size=EMBEDDING_BATCH_SIZE,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
)

embedding_seconds = time.perf_counter() - embedding_start

print(f"Embedding matrix shape: {fit_embeddings.shape}")
print(f"Embedding time:         {embedding_seconds:.1f} seconds")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/40 [00:00<?, ?it/s]

Embedding matrix shape: (5000, 384)
Embedding time:         9.3 seconds

## 6. Shared topic-evaluation functions

In [ ]:
def normalize_topic_words(raw_topics, top_n=TOP_N_WORDS):
    """Convert BERTopic/FASTopic topic outputs to list[list[str]]."""

    normalized = []

    if isinstance(raw_topics, dict):
        iterable = [
            value
            for topic_id, value in raw_topics.items()
            if int(topic_id) != -1
        ]
    else:
        iterable = raw_topics

    for topic in iterable:
        if topic is None:
            continue

        if isinstance(topic, str):
            words = topic.split()
        else:
            words = []
            for item in topic:
                if isinstance(item, (tuple, list)) and item:
                    word = item[0]
                else:
                    word = item

                word = str(word).strip()
                if word:
                    words.append(word)

        words = list(dict.fromkeys(words))[:top_n]
        if words:
            normalized.append(words)

    return normalized


def topic_diversity(topic_words, top_n=TOP_N_WORDS):
    truncated = [topic[:top_n] for topic in topic_words if topic]
    total_words = sum(len(topic) for topic in truncated)

    if total_words == 0:
        return np.nan

    unique_words = {
        word
        for topic in truncated
        for word in topic
    }

    return len(unique_words) / total_words


def compute_topic_metrics(
    topic_words,
    documents,
    top_n=TOP_N_WORDS,
):
    """Compute C_v, NPMI, U_Mass, and topic diversity."""

    if len(documents) > MAX_DOCS_FOR_COHERENCE:
        rng = np.random.default_rng(SEED)
        selected_indices = rng.choice(
            len(documents),
            size=MAX_DOCS_FOR_COHERENCE,
            replace=False,
        )
        evaluation_docs = [
            documents[index]
            for index in selected_indices
        ]
    else:
        evaluation_docs = documents

    analyzer = CountVectorizer(
        stop_words="english",
        token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z]+\b",
    ).build_analyzer()

    tokenized_docs = [
        analyzer(document)
        for document in evaluation_docs
    ]
    tokenized_docs = [
        tokens
        for tokens in tokenized_docs
        if tokens
    ]

    dictionary = Dictionary(tokenized_docs)
    corpus = [
        dictionary.doc2bow(tokens)
        for tokens in tokenized_docs
    ]

    valid_topics = []
    for topic in topic_words:
        valid_words = [
            word
            for word in topic[:top_n]
            if word in dictionary.token2id
        ]
        if len(valid_words) >= 2:
            valid_topics.append(valid_words)

    if not valid_topics:
        return {
            "c_v": np.nan,
            "c_npmi": np.nan,
            "u_mass": np.nan,
            "topic_diversity": np.nan,
            "evaluated_topics": 0,
        }

    common_arguments = {
        "topics": valid_topics,
        "dictionary": dictionary,
        "processes": 1,
    }

    c_v = CoherenceModel(
        texts=tokenized_docs,
        coherence="c_v",
        **common_arguments,
    ).get_coherence()

    c_npmi = CoherenceModel(
        texts=tokenized_docs,
        coherence="c_npmi",
        **common_arguments,
    ).get_coherence()

    u_mass = CoherenceModel(
        corpus=corpus,
        coherence="u_mass",
        **common_arguments,
    ).get_coherence()

    return {
        "c_v": float(c_v),
        "c_npmi": float(c_npmi),
        "u_mass": float(u_mass),
        "topic_diversity": float(
            topic_diversity(valid_topics, top_n=top_n)
        ),
        "evaluated_topics": len(valid_topics),
    }


def topic_table(topic_words, model_name):
    rows = []
    for topic_id, words in enumerate(topic_words):
        rows.append(
            {
                "model": model_name,
                "topic_id": topic_id,
                "topic_label": ", ".join(words[:5]),
                "top_words": ", ".join(words),
            }
        )
    return pd.DataFrame(rows)

## 7. Fit BERTopic

In [ ]:
bertopic_vectorizer = CountVectorizer(
    stop_words="english",
    min_df=2,
    max_df=0.95,
    ngram_range=(1, 2),
)

bertopic_umap = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=SEED,
)

minimum_cluster_size = max(
    15,
    min(100, len(fit_docs) // 200),
)

bertopic_hdbscan = HDBSCAN(
    min_cluster_size=minimum_cluster_size,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True,
)

bertopic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=bertopic_umap,
    hdbscan_model=bertopic_hdbscan,
    vectorizer_model=bertopic_vectorizer,
    nr_topics=N_TOPICS,
    top_n_words=TOP_N_WORDS,
    calculate_probabilities=False,
    verbose=True,
)

bertopic_start = time.perf_counter()

bertopic_topics, _ = bertopic_model.fit_transform(
    fit_docs,
    fit_embeddings,
)

bertopic_seconds = time.perf_counter() - bertopic_start

bertopic_topic_words = normalize_topic_words(
    bertopic_model.get_topics()
)

bertopic_metrics = compute_topic_metrics(
    bertopic_topic_words,
    fit_docs,
)

bertopic_outlier_rate = float(
    np.mean(np.asarray(bertopic_topics) == -1)
)

print(f"BERTopic runtime:      {bertopic_seconds:.1f} seconds")
print(f"BERTopic topics:       {len(bertopic_topic_words)}")
print(f"BERTopic outlier rate: {bertopic_outlier_rate:.1%}")
print(bertopic_metrics)

topic_table(
    bertopic_topic_words,
    "BERTopic",
).head(20)

2026-07-28 14:30:36,828 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-28 14:31:12,994 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:31:12,995 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-28 14:31:13,341 - BERTopic - Cluster - Completed ✓
2026-07-28 14:31:13,342 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-07-28 14:31:14,500 - BERTopic - Representation - Completed ✓
2026-07-28 14:31:14,501 - BERTopic - Topic reduction - Reducing number of topics
2026-07-28 14:31:14,518 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-28 14:31:15,660 - BERTopic - Representation - Completed ✓
2026-07-28 14:31:15,664 - BERTopic - Topic reduction - Reduced number of topics from 27 to 25

BERTopic runtime:      39.4 seconds
BERTopic topics:       24
BERTopic outlier rate: 27.7%
{'c_v': 0.63817339948035, 'c_npmi': 0.09885825422138776, 'u_mass': -3.51733277788149, 'topic_diversity': 0.9203539823008849, 'evaluated_topics': 24}

,model,topic_id,topic_label,top_words
0,BERTopic,0,"car, store, customer, said, business","car, store, customer, said, business, job, sho..."
1,BERTopic,1,"dr, doctor, appointment, pain, care","dr, doctor, appointment, pain, care, office, s..."
2,BERTopic,2,"tacos, food, sandwich, chicken, taco","tacos, food, sandwich, chicken, taco, mexican,..."
3,BERTopic,3,"wine, tasting, wines, bar, tour","wine, tasting, wines, bar, tour, beer, drinks,..."
4,BERTopic,4,"room, hotel, stay, night, clean","room, hotel, stay, night, clean, bed, rooms, a..."
5,BERTopic,5,"hair, cut, salon, haircut, stylist","hair, cut, salon, haircut, stylist, color, hai..."
6,BERTopic,6,"wedding, event, venue, planning, guests","wedding, event, venue, planning, guests, team,..."
7,BERTopic,7,"dog, dogs, cat, pet, cats","dog, dogs, cat, pet, cats, puppy, care, animal..."
8,BERTopic,8,"dr, dentist, dental, teeth, office","dr, dentist, dental, teeth, office, insurance,..."
9,BERTopic,9,"gym, workout, classes, class, workouts","gym, workout, classes, class, workouts, studio..."
10,BERTopic,10,"beach, trail, hike, beautiful, park","beach, trail, hike, beautiful, park, view, vie..."
11,BERTopic,11,"massage, massages, spa, body, relax","massage, massages, spa, body, relax, deep tiss..."
12,BERTopic,12,"photos, wedding, photographer, pictures, photo","photos, wedding, photographer, pictures, photo..."
13,BERTopic,13,"thai, food, chinese, noodles, chicken","thai, food, chinese, noodles, chicken, spicy, ..."
14,BERTopic,14,"nails, nail, mani, pedi, mani pedi","nails, nail, mani, pedi, mani pedi, gel, tip, ..."
15,BERTopic,15,"coffee, starbucks, drink, location, drinks","coffee, starbucks, drink, location, drinks, or..."
16,BERTopic,16,"pizza, crust, pizzas, pizza good, ordered","pizza, crust, pizzas, pizza good, ordered, piz..."
17,BERTopic,17,"cream, ice, ice cream, yogurt, smoothie","cream, ice, ice cream, yogurt, smoothie, flavo..."
18,BERTopic,18,"wax, waxing, brazilian, eyebrows, salon","wax, waxing, brazilian, eyebrows, salon, jenn,..."
19,BERTopic,19,"makeup, hair, wedding, hair makeup, emily","makeup, hair, wedding, hair makeup, emily, wed..."

## 8. Save BERTopic

In [ ]:
BERTOPIC_MODEL_PATH = OUTPUT_DIR / "bertopic_yelp_model"

bertopic_model.save(
    str(BERTOPIC_MODEL_PATH),
    serialization="safetensors",
    save_ctfidf=True,
    save_embedding_model=EMBEDDING_MODEL_NAME,
)

topic_table(
    bertopic_topic_words,
    "BERTopic",
).to_csv(
    OUTPUT_DIR / "bertopic_topics.csv",
    index=False,
)

print(f"Saved BERTopic model to: {BERTOPIC_MODEL_PATH}")

Saved BERTopic model to: /content/drive/MyDrive/yelp_topic_modeling/bertopic_yelp_model

## 9. Fit FASTopic

In [ ]:
fastopic_preprocess = Preprocess(
    vocab_size=10_000,
)

fastopic_model = FASTopic(
    num_topics=N_TOPICS,
    preprocess=fastopic_preprocess,
    doc_embed_model=embedding_model,
    device=DEVICE,
    normalize_embeddings=True,
    low_memory=True,
    low_memory_batch_size=2_000,
    verbose=True,
)

fastopic_start = time.perf_counter()

fastopic_raw_topics, fastopic_doc_topic_dist = (
    fastopic_model.fit_transform(
        fit_docs,
        epochs=FASTOPIC_EPOCHS,
        learning_rate=0.01,
    )
)

fastopic_seconds = time.perf_counter() - fastopic_start

fastopic_topic_words = normalize_topic_words(
    fastopic_raw_topics
)

fastopic_metrics = compute_topic_metrics(
    fastopic_topic_words,
    fit_docs,
)

print(f"FASTopic runtime: {fastopic_seconds:.1f} seconds")
print(f"FASTopic topics:  {len(fastopic_topic_words)}")
print(fastopic_metrics)

topic_table(
    fastopic_topic_words,
    "FASTopic",
).head(20)

2026-07-28 14:31:28,203 - FASTopic - use device: cuda
2026-07-28 14:31:28,204 - FASTopic - Using low memory mode.
2026-07-28 14:31:28,205 - FASTopic - First fit the model.
loading train texts: 100%|██████████| 5000/5000 [00:01<00:00, 3638.66it/s]
parsing texts: 100%|██████████| 5000/5000 [00:00<00:00, 7582.79it/s]
2026-07-28 14:31:30,428 - TopMost - Real vocab size: 10000
2026-07-28 14:31:30,429 - TopMost - Real training size: 5000 	 avg length: 41.414

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Training FASTopic:  90%|█████████ | 9/10 [00:05<00:00,  1.47it/s]2026-07-28 14:31:44,024 - FASTopic - Epoch: 010 loss: 343.347
Training FASTopic: 100%|██████████| 10/10 [00:06<00:00,  1.51it/s]

Topic 0: body pain results nails treatment salon cut health nail surgery physical skin gentle neck haircut
Topic 1: cockroach furious ihop chatting stations remake everytime existent yea atrocious nope registers established creepy racist
Topic 2: store shop buy stores sales gift clothes bought sale prices items item sell stock purchase
Topic 3: wedding photos process helped ceremony planning event budget photo events training reception flowers beginning team
Topic 4: branch atm scam banks banking quoted claimed debit verizon funds plumber collections defensive lied idiot
Topic 5: food restaurant ordered breakfast chicken menu beer burger meal sandwich fries eat served sauce meat
Topic 6: study straws lattes mud outdated hostel stench campsite blocks ppl downstairs halls stink entry maneuver
Topic 7: brunch culinary shawarma mahi bagel ceviche divine horchata deliciousness braised sausages glaze brussel vegetarians steaks
Topic 8: car repair cleaning crew tree parts replaced vehicle wash auto windows repairs companies paint estimate
Topic 9: cameron valencia raisin eos turtles americano karims colonial karim stix mornings boujee studied baklava hoppy
Topic 10: paul mahneke neglect spark howling viking corporation stephen refinance negotiated hoa mena escalera advisor wireless
Topic 11: musical puppy taylor jorge raquel optometrist raphael acupuncturist wency connie modalities nurturing shining landscaping lumsden
Topic 12: boutique funk gem spacious plants toys selections donuts museum art books library zone cutest hang
Topic 13: remodeled guitar puzzles barbers travelling fits instrument puzzle fritter toni lions trunks socialize instruments foothills
Topic 14: foreign currency kits shoe purse multitude tellers shopped queue module electronic airline tow chase windshield
Topic 15: massage classes gym relaxing workout studio relaxed fabulous massages loves instructor class fitness yoga dance
Topic 16: barber reasonably barbershop knitting tidy knit jude mitchell strands bounce diani worship legend leashes marie
Topic 17: said told paid horrible worst terrible charged minutes asked credit pay waited rude called phone
Topic 18: room stay hotel parking bathroom rooms bike bed pool water train stayed station drive gas
Topic 19: makeup wax talented lashes waxing artist personality michelle anna emily mia laurie stylist austin flawless
Topic 20: pizza ingredients yummy chocolate sushi cream italian toppings yogurt milk flavors veggies vegan organic cupcakes
Topic 21: wine tasting party wines tour enjoy play birthday enjoyed glass ucsb private barbara group visiting
Topic 22: dentist dental insurance teeth procedure legal patients rays attorney dentists pharmacy clinic doctors performed prescription
Topic 23: rainbow theaters monarchs carlas roses cottages lend blink zoom carousel museums francis twin puzzles foothills
Topic 24: puppy cvs lapatka hydro caregiver nerves specialized pets ethic implants migraines tests addresses precisely feld
FASTopic runtime: 16.0 seconds
FASTopic topics:  25
{'c_v': 0.47721590733840286, 'c_npmi': -0.20879551247031167, 'u_mass': -13.203868089465278, 'topic_diversity': 0.9959677419354839, 'evaluated_topics': 25}

,model,topic_id,topic_label,top_words
0,FASTopic,0,"body, pain, results, nails, treatment","body, pain, results, nails, treatment, salon, ..."
1,FASTopic,1,"cockroach, furious, ihop, chatting, stations","cockroach, furious, ihop, chatting, stations, ..."
2,FASTopic,2,"store, shop, buy, stores, sales","store, shop, buy, stores, sales, gift, clothes..."
3,FASTopic,3,"wedding, photos, process, helped, ceremony","wedding, photos, process, helped, ceremony, pl..."
4,FASTopic,4,"branch, atm, scam, banks, banking","branch, atm, scam, banks, banking, quoted, cla..."
5,FASTopic,5,"food, restaurant, ordered, breakfast, chicken","food, restaurant, ordered, breakfast, chicken,..."
6,FASTopic,6,"study, straws, lattes, mud, outdated","study, straws, lattes, mud, outdated, hostel, ..."
7,FASTopic,7,"brunch, culinary, shawarma, mahi, bagel","brunch, culinary, shawarma, mahi, bagel, cevic..."
8,FASTopic,8,"car, repair, cleaning, crew, tree","car, repair, cleaning, crew, tree, parts, repl..."
9,FASTopic,9,"cameron, valencia, raisin, eos, turtles","cameron, valencia, raisin, eos, turtles, ameri..."
10,FASTopic,10,"paul, mahneke, neglect, spark, howling","paul, mahneke, neglect, spark, howling, viking..."
11,FASTopic,11,"musical, puppy, taylor, jorge, raquel","musical, puppy, taylor, jorge, raquel, optomet..."
12,FASTopic,12,"boutique, funk, gem, spacious, plants","boutique, funk, gem, spacious, plants, toys, s..."
13,FASTopic,13,"remodeled, guitar, puzzles, barbers, travelling","remodeled, guitar, puzzles, barbers, travellin..."
14,FASTopic,14,"foreign, currency, kits, shoe, purse","foreign, currency, kits, shoe, purse, multitud..."
15,FASTopic,15,"massage, classes, gym, relaxing, workout","massage, classes, gym, relaxing, workout, stud..."
16,FASTopic,16,"barber, reasonably, barbershop, knitting, tidy","barber, reasonably, barbershop, knitting, tidy..."
17,FASTopic,17,"said, told, paid, horrible, worst","said, told, paid, horrible, worst, terrible, c..."
18,FASTopic,18,"room, stay, hotel, parking, bathroom","room, stay, hotel, parking, bathroom, rooms, b..."
19,FASTopic,19,"makeup, wax, talented, lashes, waxing","makeup, wax, talented, lashes, waxing, artist,..."

## 10. Save FASTopic

In [ ]:
FAST_TOPIC_MODEL_PATH = OUTPUT_DIR / "fastopic_yelp_model.zip"

fastopic_model.save(
    str(FAST_TOPIC_MODEL_PATH)
)

topic_table(
    fastopic_topic_words,
    "FASTopic",
).to_csv(
    OUTPUT_DIR / "fastopic_topics.csv",
    index=False,
)

print(f"Saved FASTopic model to: {FAST_TOPIC_MODEL_PATH}")

Saved FASTopic model to: /content/drive/MyDrive/yelp_topic_modeling/fastopic_yelp_model.zip

## 11. Compare the models

In [ ]:
comparison_df = pd.DataFrame(
    [
        {
            "model": "BERTopic",
            "fit_documents": len(fit_docs),
            "number_of_topics": len(bertopic_topic_words),
            "c_v": bertopic_metrics["c_v"],
            "c_npmi": bertopic_metrics["c_npmi"],
            "u_mass": bertopic_metrics["u_mass"],
            "topic_diversity": bertopic_metrics[
                "topic_diversity"
            ],
            "fit_seconds": bertopic_seconds,
            "outlier_rate": bertopic_outlier_rate,
        },
        {
            "model": "FASTopic",
            "fit_documents": len(fit_docs),
            "number_of_topics": len(fastopic_topic_words),
            "c_v": fastopic_metrics["c_v"],
            "c_npmi": fastopic_metrics["c_npmi"],
            "u_mass": fastopic_metrics["u_mass"],
            "topic_diversity": fastopic_metrics[
                "topic_diversity"
            ],
            "fit_seconds": fastopic_seconds,
            "outlier_rate": np.nan,
        },
    ]
)

# Higher is better for all four quality metrics, including U_Mass
# where a value closer to zero is generally better.
quality_metrics = [
    "c_v",
    "c_npmi",
    "u_mass",
    "topic_diversity",
]

for metric in quality_metrics:
    comparison_df[f"{metric}_rank"] = (
        comparison_df[metric]
        .rank(ascending=False, method="min")
    )

comparison_df["mean_quality_rank"] = comparison_df[
    [f"{metric}_rank" for metric in quality_metrics]
].mean(axis=1)

comparison_df = comparison_df.sort_values(
    ["mean_quality_rank", "fit_seconds"]
).reset_index(drop=True)

comparison_df.to_csv(
    OUTPUT_DIR / "topic_model_comparison.csv",
    index=False,
)

comparison_df

,model,fit_documents,number_of_topics,c_v,c_npmi,u_mass,topic_diversity,fit_seconds,outlier_rate,c_v_rank,c_npmi_rank,u_mass_rank,topic_diversity_rank,mean_quality_rank
0,BERTopic,5000,24,0.638173,0.098858,-3.517333,0.920354,39.424430,0.2774,1.0,1.0,1.0,2.0,1.25
1,FASTopic,5000,25,0.477216,-0.208796,-13.203868,0.995968,16.028684,NaN,2.0,2.0,2.0,1.0,1.75

### Interpretation

- Higher C_v is better.
- Higher NPMI is better.
- Higher U_Mass is better; it is commonly negative, so values closer to zero
  are better.
- Higher topic diversity is better, but diversity should not be interpreted
  without inspecting coherence.
- Review the topic words and representative documents manually before choosing
  the production model.

## 12. Inspect representative topics

In [ ]:
print("BERTopic topics")
display(topic_table(bertopic_topic_words, "BERTopic").head(15))

print("\nFASTopic topics")
display(topic_table(fastopic_topic_words, "FASTopic").head(15))

print("\nBERTopic representative documents")
for topic_id in range(min(5, len(bertopic_topic_words))):
    representatives = (
        bertopic_model.get_representative_docs(topic_id)
        or []
    )
    print(f"\nTopic {topic_id}: {bertopic_topic_words[topic_id][:5]}")
    for document in representatives[:2]:
        print(" -", document[:300].replace("\n", " "))

BERTopic topics

,model,topic_id,topic_label,top_words
0,BERTopic,0,"car, store, customer, said, business","car, store, customer, said, business, job, sho..."
1,BERTopic,1,"dr, doctor, appointment, pain, care","dr, doctor, appointment, pain, care, office, s..."
2,BERTopic,2,"tacos, food, sandwich, chicken, taco","tacos, food, sandwich, chicken, taco, mexican,..."
3,BERTopic,3,"wine, tasting, wines, bar, tour","wine, tasting, wines, bar, tour, beer, drinks,..."
4,BERTopic,4,"room, hotel, stay, night, clean","room, hotel, stay, night, clean, bed, rooms, a..."
5,BERTopic,5,"hair, cut, salon, haircut, stylist","hair, cut, salon, haircut, stylist, color, hai..."
6,BERTopic,6,"wedding, event, venue, planning, guests","wedding, event, venue, planning, guests, team,..."
7,BERTopic,7,"dog, dogs, cat, pet, cats","dog, dogs, cat, pet, cats, puppy, care, animal..."
8,BERTopic,8,"dr, dentist, dental, teeth, office","dr, dentist, dental, teeth, office, insurance,..."
9,BERTopic,9,"gym, workout, classes, class, workouts","gym, workout, classes, class, workouts, studio..."
10,BERTopic,10,"beach, trail, hike, beautiful, park","beach, trail, hike, beautiful, park, view, vie..."
11,BERTopic,11,"massage, massages, spa, body, relax","massage, massages, spa, body, relax, deep tiss..."
12,BERTopic,12,"photos, wedding, photographer, pictures, photo","photos, wedding, photographer, pictures, photo..."
13,BERTopic,13,"thai, food, chinese, noodles, chicken","thai, food, chinese, noodles, chicken, spicy, ..."
14,BERTopic,14,"nails, nail, mani, pedi, mani pedi","nails, nail, mani, pedi, mani pedi, gel, tip, ..."

FASTopic topics

,model,topic_id,topic_label,top_words
0,FASTopic,0,"body, pain, results, nails, treatment","body, pain, results, nails, treatment, salon, ..."
1,FASTopic,1,"cockroach, furious, ihop, chatting, stations","cockroach, furious, ihop, chatting, stations, ..."
2,FASTopic,2,"store, shop, buy, stores, sales","store, shop, buy, stores, sales, gift, clothes..."
3,FASTopic,3,"wedding, photos, process, helped, ceremony","wedding, photos, process, helped, ceremony, pl..."
4,FASTopic,4,"branch, atm, scam, banks, banking","branch, atm, scam, banks, banking, quoted, cla..."
5,FASTopic,5,"food, restaurant, ordered, breakfast, chicken","food, restaurant, ordered, breakfast, chicken,..."
6,FASTopic,6,"study, straws, lattes, mud, outdated","study, straws, lattes, mud, outdated, hostel, ..."
7,FASTopic,7,"brunch, culinary, shawarma, mahi, bagel","brunch, culinary, shawarma, mahi, bagel, cevic..."
8,FASTopic,8,"car, repair, cleaning, crew, tree","car, repair, cleaning, crew, tree, parts, repl..."
9,FASTopic,9,"cameron, valencia, raisin, eos, turtles","cameron, valencia, raisin, eos, turtles, ameri..."
10,FASTopic,10,"paul, mahneke, neglect, spark, howling","paul, mahneke, neglect, spark, howling, viking..."
11,FASTopic,11,"musical, puppy, taylor, jorge, raquel","musical, puppy, taylor, jorge, raquel, optomet..."
12,FASTopic,12,"boutique, funk, gem, spacious, plants","boutique, funk, gem, spacious, plants, toys, s..."
13,FASTopic,13,"remodeled, guitar, puzzles, barbers, travelling","remodeled, guitar, puzzles, barbers, travellin..."
14,FASTopic,14,"foreign, currency, kits, shoe, purse","foreign, currency, kits, shoe, purse, multitud..."

BERTopic representative documents

Topic 0: ['car', 'store', 'customer', 'said', 'business']
 - I took a small wool shag rug in to be cleaned after about a year of hard use. This place had a few good reviews around the internets, and they had their price list on the web site, which I appreciated. The drop-off went pretty well--I choose my options and pre-paid, noting the passive-aggressive sig
 - I've only written a couple of reviews in my life, but I wanted to take the time to write this one. I'm also a hyper-critical college professor and rarely give A's, never A-pluses. But I have to say, John Biggs and his crew at Anacapa are car restoration WIZARDS; I give them a firm and enthusiastic A

Topic 1: ['dr', 'doctor', 'appointment', 'pain', 'care']
 - This review is specific to Dr. Ehsani who is an extremely unprofessional doctor at JMG. Every test he orders for me I have to call the office multiple times leaving messages for him before he will return my call with the results. Additionally he does not listen to my symptoms and medical history bef
 - I've been seeing Dr. Schuyler for over a year and a half and the treatments I have received from him have been nothing short of life changing. When I found Dr. Schuyler I had been experiencing 3.5 years of daily chronic lower back pain. I was impressed with his professional, scientific approach in o

Topic 2: ['tacos', 'food', 'sandwich', 'chicken', 'taco']
 - Went to the grand opening of Rascal's new location on 18 E Cota. It was pretty busy, which was great to see. Took some teenagers and my parents and we tried a bunch of items. Only 2/7 of us were vegan/vegetarian. Service was great. They were honest about the wait and I really appreciated that. Super
 - I came here once when it first opened and it was a bit chaotic. Yesterday I decided to have lunch and see how it is since they are more established. Needless to say, I was very disappointed. I like to say that Mexican food is like pizzas, some are better than others but they are all good...well, not

Topic 3: ['wine', 'tasting', 'wines', 'bar', 'tour']
 - Terrible experience at Fox, and Yelp let me down on this one. Funky set up as space is shared with a food spot (Nook) and a brewery (Topa Topa). And they don't seem to play together well. It's like a stupid TV show or movie where cohabitants draw a line in the middle of a room and pretend the other
 - Took this tour with a couple friends and had a great time. Off the Vine Wine Tours was recommended to us by some friends and we booked a Sunday tour for four. We were picked up promptly and the vehicle was nice. As we enjoyed the scenic ride up to Santa Ynez our guide told us some information about

Topic 4: ['room', 'hotel', 'stay', 'night', 'clean']
 - I have lost count of how many times I have stayed at the BW Carpinteria Inn. This does not mean that I love this place, I have mostly found myself here by default. I want to love this place...I really do. Let me explain, I mostly stay here when the good hotels in Santa Barbara are sold out, and I do
 - I chose it based on the lovely pictures. My experience with the Villa Rosa Inn began before I stepped foot on the property. On the morning of the day I was to check in, I received a call telling me that the room I had selected had been given to someone else by one of the new employees in training. I

## 13. Assign the selected model to all reviews and export business topics

Leave `RUN_FULL_DATA_INFERENCE = False` during testing. After reviewing the
comparison, set it to `True`, choose `SELECTED_MODEL_FOR_EXPORT`, and rerun this
cell.

This is offline preprocessing. The Shiny app should load the resulting compact
business-level CSV instead of running topic models in real time.

In [ ]:
def infer_bertopic_in_batches(documents):
    all_topic_ids = []
    all_topic_scores = []

    for start in range(0, len(documents), INFERENCE_BATCH_SIZE):
        batch_docs = documents[
            start:start + INFERENCE_BATCH_SIZE
        ]

        batch_embeddings = embedding_model.encode(
            batch_docs,
            batch_size=EMBEDDING_BATCH_SIZE,
            show_progress_bar=False,
            convert_to_numpy=True,
            normalize_embeddings=True,
        )

        batch_topics, batch_probabilities = (
            bertopic_model.transform(
                batch_docs,
                batch_embeddings,
            )
        )

        all_topic_ids.extend(
            int(topic_id)
            for topic_id in batch_topics
        )

        if batch_probabilities is None:
            all_topic_scores.extend(
                [np.nan] * len(batch_topics)
            )
        else:
            probability_array = np.asarray(
                batch_probabilities
            )
            if probability_array.ndim == 1:
                all_topic_scores.extend(
                    probability_array.astype(float).tolist()
                )
            else:
                all_topic_scores.extend(
                    probability_array.max(axis=1)
                    .astype(float)
                    .tolist()
                )

        print(
            f"BERTopic inference: "
            f"{min(start + len(batch_docs), len(documents)):,}/"
            f"{len(documents):,}"
        )

    return all_topic_ids, all_topic_scores


def infer_fastopic_in_batches(documents):
    all_topic_ids = []
    all_topic_scores = []

    for start in range(0, len(documents), INFERENCE_BATCH_SIZE):
        batch_docs = documents[
            start:start + INFERENCE_BATCH_SIZE
        ]

        batch_distribution = np.asarray(
            fastopic_model.transform(batch_docs)
        )

        all_topic_ids.extend(
            batch_distribution.argmax(axis=1)
            .astype(int)
            .tolist()
        )
        all_topic_scores.extend(
            batch_distribution.max(axis=1)
            .astype(float)
            .tolist()
        )

        print(
            f"FASTopic inference: "
            f"{min(start + len(batch_docs), len(documents)):,}/"
            f"{len(documents):,}"
        )

    return all_topic_ids, all_topic_scores


if RUN_FULL_DATA_INFERENCE:
    all_docs = reviews_df.get_column(TEXT_COL).to_list()

    if SELECTED_MODEL_FOR_EXPORT == "BERTopic":
        selected_topic_words = bertopic_topic_words
        topic_ids, topic_scores = infer_bertopic_in_batches(
            all_docs
        )
    elif SELECTED_MODEL_FOR_EXPORT == "FASTopic":
        selected_topic_words = fastopic_topic_words
        topic_ids, topic_scores = infer_fastopic_in_batches(
            all_docs
        )
    else:
        raise ValueError(
            "SELECTED_MODEL_FOR_EXPORT must be "
            "'BERTopic' or 'FASTopic'."
        )

    assigned_df = pd.DataFrame(
        {
            "business_id": reviews_df
            .get_column(BUSINESS_ID_COL)
            .to_list(),
            "business_name": reviews_df
            .get_column(BUSINESS_NAME_COL)
            .to_list(),
            "topic_id": topic_ids,
            "topic_score": topic_scores,
        }
    )

    # BERTopic topic -1 is the outlier topic and is excluded from
    # business-level ranked topics.
    assigned_non_outliers = assigned_df[
        assigned_df["topic_id"] >= 0
    ].copy()

    topic_labels = {
        topic_id: ", ".join(words[:5])
        for topic_id, words in enumerate(
            selected_topic_words
        )
    }

    assigned_non_outliers["topic_label"] = (
        assigned_non_outliers["topic_id"]
        .map(topic_labels)
        .fillna("Unlabeled topic")
    )

    business_topic_summary = (
        assigned_non_outliers
        .groupby(
            [
                "business_id",
                "business_name",
                "topic_id",
                "topic_label",
            ],
            as_index=False,
        )
        .agg(
            topic_review_count=("topic_id", "size"),
            average_topic_score=("topic_score", "mean"),
        )
    )

    business_topic_summary["business_assigned_reviews"] = (
        business_topic_summary
        .groupby("business_id")["topic_review_count"]
        .transform("sum")
    )

    business_topic_summary["topic_share"] = (
        business_topic_summary["topic_review_count"]
        / business_topic_summary["business_assigned_reviews"]
    )

    business_topic_summary["topic_rank"] = (
        business_topic_summary
        .groupby("business_id")["topic_review_count"]
        .rank(
            method="first",
            ascending=False,
        )
        .astype(int)
    )

    business_top_topics = (
        business_topic_summary[
            business_topic_summary["topic_rank"] <= 5
        ]
        .sort_values(
            ["business_name", "topic_rank"]
        )
        .reset_index(drop=True)
    )

    business_top_topics["model"] = (
        SELECTED_MODEL_FOR_EXPORT
    )

    review_output_path = (
        OUTPUT_DIR
        / "review_topic_assignments.parquet"
    )
    business_output_path = (
        OUTPUT_DIR
        / "business_top_topics.csv"
    )

    assigned_df.to_parquet(
        review_output_path,
        index=False,
    )
    business_top_topics.to_csv(
        business_output_path,
        index=False,
    )

    print(f"Saved review assignments: {review_output_path}")
    print(f"Saved business topics:     {business_output_path}")
    display(business_top_topics.head(20))
else:
    print(
        "Full-data inference is disabled. "
        "Set RUN_FULL_DATA_INFERENCE = True after selecting a model."
    )

2026-07-28 14:33:54,148 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:15,619 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:15,621 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:15,702 - BERTopic - Cluster - Completed ✓

BERTopic inference: 2,000/346,772

2026-07-28 14:34:18,544 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:19,476 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:19,478 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:19,561 - BERTopic - Cluster - Completed ✓

BERTopic inference: 4,000/346,772

2026-07-28 14:34:23,002 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:24,349 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:24,350 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:24,473 - BERTopic - Cluster - Completed ✓

BERTopic inference: 6,000/346,772

2026-07-28 14:34:27,288 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:28,250 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:28,251 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:28,331 - BERTopic - Cluster - Completed ✓

BERTopic inference: 8,000/346,772

2026-07-28 14:34:31,125 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:32,092 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:32,093 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:32,179 - BERTopic - Cluster - Completed ✓

BERTopic inference: 10,000/346,772

2026-07-28 14:34:35,016 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:36,303 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:36,306 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:36,444 - BERTopic - Cluster - Completed ✓

BERTopic inference: 12,000/346,772

2026-07-28 14:34:40,034 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:40,992 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:40,993 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:41,067 - BERTopic - Cluster - Completed ✓

BERTopic inference: 14,000/346,772

2026-07-28 14:34:43,846 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:44,789 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:44,790 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:44,883 - BERTopic - Cluster - Completed ✓

BERTopic inference: 16,000/346,772

2026-07-28 14:34:47,735 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:48,692 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:48,693 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:48,770 - BERTopic - Cluster - Completed ✓

BERTopic inference: 18,000/346,772

2026-07-28 14:34:52,396 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:53,794 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:53,795 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:53,872 - BERTopic - Cluster - Completed ✓

BERTopic inference: 20,000/346,772

2026-07-28 14:34:56,806 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:34:57,727 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:34:57,728 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:34:57,809 - BERTopic - Cluster - Completed ✓

BERTopic inference: 22,000/346,772

2026-07-28 14:35:00,725 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:01,782 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:01,783 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:01,865 - BERTopic - Cluster - Completed ✓

BERTopic inference: 24,000/346,772

2026-07-28 14:35:04,911 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:06,196 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:06,198 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:06,320 - BERTopic - Cluster - Completed ✓

BERTopic inference: 26,000/346,772

2026-07-28 14:35:09,575 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:10,521 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:10,521 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:10,595 - BERTopic - Cluster - Completed ✓

BERTopic inference: 28,000/346,772

2026-07-28 14:35:13,512 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:15,036 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:15,037 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:15,111 - BERTopic - Cluster - Completed ✓

BERTopic inference: 30,000/346,772

2026-07-28 14:35:18,075 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:19,309 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:19,310 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:19,434 - BERTopic - Cluster - Completed ✓

BERTopic inference: 32,000/346,772

2026-07-28 14:35:23,142 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:24,061 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:24,062 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:24,142 - BERTopic - Cluster - Completed ✓

BERTopic inference: 34,000/346,772

2026-07-28 14:35:27,071 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:28,016 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:28,017 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:28,094 - BERTopic - Cluster - Completed ✓

BERTopic inference: 36,000/346,772

2026-07-28 14:35:30,934 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:31,930 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:31,931 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:32,015 - BERTopic - Cluster - Completed ✓

BERTopic inference: 38,000/346,772

2026-07-28 14:35:35,337 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:36,666 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:36,667 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:36,795 - BERTopic - Cluster - Completed ✓

BERTopic inference: 40,000/346,772

2026-07-28 14:35:39,921 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:40,861 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:40,862 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:40,939 - BERTopic - Cluster - Completed ✓

BERTopic inference: 42,000/346,772

2026-07-28 14:35:43,771 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:44,795 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:44,796 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:44,870 - BERTopic - Cluster - Completed ✓

BERTopic inference: 44,000/346,772

2026-07-28 14:35:47,872 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:49,184 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:49,186 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:49,307 - BERTopic - Cluster - Completed ✓

BERTopic inference: 46,000/346,772

2026-07-28 14:35:52,860 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:53,833 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:53,834 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:53,912 - BERTopic - Cluster - Completed ✓

BERTopic inference: 48,000/346,772

2026-07-28 14:35:57,564 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:35:58,496 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:35:58,497 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:35:58,571 - BERTopic - Cluster - Completed ✓

BERTopic inference: 50,000/346,772

2026-07-28 14:36:01,601 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:02,669 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:02,670 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:02,813 - BERTopic - Cluster - Completed ✓

BERTopic inference: 52,000/346,772

2026-07-28 14:36:06,578 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:07,553 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:07,554 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:07,628 - BERTopic - Cluster - Completed ✓

BERTopic inference: 54,000/346,772

2026-07-28 14:36:10,526 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:11,554 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:11,555 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:11,633 - BERTopic - Cluster - Completed ✓

BERTopic inference: 56,000/346,772

2026-07-28 14:36:14,593 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:15,543 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:15,544 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:15,615 - BERTopic - Cluster - Completed ✓

BERTopic inference: 58,000/346,772

2026-07-28 14:36:18,871 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:20,169 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:20,171 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:20,305 - BERTopic - Cluster - Completed ✓

BERTopic inference: 60,000/346,772

2026-07-28 14:36:23,431 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:24,419 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:24,420 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:24,496 - BERTopic - Cluster - Completed ✓

BERTopic inference: 62,000/346,772

2026-07-28 14:36:27,443 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:28,387 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:28,388 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:28,472 - BERTopic - Cluster - Completed ✓

BERTopic inference: 64,000/346,772

2026-07-28 14:36:31,430 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:32,754 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:32,756 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:32,874 - BERTopic - Cluster - Completed ✓

BERTopic inference: 66,000/346,772

2026-07-28 14:36:36,532 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:37,472 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:37,473 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:37,549 - BERTopic - Cluster - Completed ✓

BERTopic inference: 68,000/346,772

2026-07-28 14:36:40,522 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:41,431 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:41,431 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:41,527 - BERTopic - Cluster - Completed ✓

BERTopic inference: 70,000/346,772

2026-07-28 14:36:44,453 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:45,406 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:45,407 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:45,488 - BERTopic - Cluster - Completed ✓

BERTopic inference: 72,000/346,772

2026-07-28 14:36:49,001 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:50,376 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:50,379 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:50,466 - BERTopic - Cluster - Completed ✓

BERTopic inference: 74,000/346,772

2026-07-28 14:36:53,424 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:54,363 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:54,364 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:54,436 - BERTopic - Cluster - Completed ✓

BERTopic inference: 76,000/346,772

2026-07-28 14:36:57,360 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:36:58,260 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:36:58,261 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:36:58,346 - BERTopic - Cluster - Completed ✓

BERTopic inference: 78,000/346,772

2026-07-28 14:37:01,512 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:02,772 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:02,774 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:02,889 - BERTopic - Cluster - Completed ✓

BERTopic inference: 80,000/346,772

2026-07-28 14:37:06,369 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:07,289 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:07,290 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:07,371 - BERTopic - Cluster - Completed ✓

BERTopic inference: 82,000/346,772

2026-07-28 14:37:10,307 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:11,256 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:11,257 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:11,341 - BERTopic - Cluster - Completed ✓

BERTopic inference: 84,000/346,772

2026-07-28 14:37:14,382 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:15,635 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:15,636 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:15,760 - BERTopic - Cluster - Completed ✓

BERTopic inference: 86,000/346,772

2026-07-28 14:37:19,629 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:20,566 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:20,567 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:20,645 - BERTopic - Cluster - Completed ✓

BERTopic inference: 88,000/346,772

2026-07-28 14:37:23,625 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:24,643 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:24,644 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:24,722 - BERTopic - Cluster - Completed ✓

BERTopic inference: 90,000/346,772

2026-07-28 14:37:27,755 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:28,678 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:28,679 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:28,769 - BERTopic - Cluster - Completed ✓

BERTopic inference: 92,000/346,772

2026-07-28 14:37:32,322 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:33,672 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:33,674 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:33,807 - BERTopic - Cluster - Completed ✓

BERTopic inference: 94,000/346,772

2026-07-28 14:37:36,966 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:37,905 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:37,906 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:37,987 - BERTopic - Cluster - Completed ✓

BERTopic inference: 96,000/346,772

2026-07-28 14:37:40,989 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:41,939 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:41,939 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:42,020 - BERTopic - Cluster - Completed ✓

BERTopic inference: 98,000/346,772

2026-07-28 14:37:45,378 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:46,683 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:46,685 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:46,800 - BERTopic - Cluster - Completed ✓

BERTopic inference: 100,000/346,772

2026-07-28 14:37:50,355 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:51,323 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:51,324 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:51,424 - BERTopic - Cluster - Completed ✓

BERTopic inference: 102,000/346,772

2026-07-28 14:37:54,530 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:37:55,496 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:37:55,497 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:37:55,573 - BERTopic - Cluster - Completed ✓

BERTopic inference: 104,000/346,772

2026-07-28 14:37:58,721 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:00,032 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:00,034 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:00,159 - BERTopic - Cluster - Completed ✓

BERTopic inference: 106,000/346,772

2026-07-28 14:38:03,897 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:04,854 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:04,855 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:04,931 - BERTopic - Cluster - Completed ✓

BERTopic inference: 108,000/346,772

2026-07-28 14:38:08,024 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:08,951 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:08,952 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:09,026 - BERTopic - Cluster - Completed ✓

BERTopic inference: 110,000/346,772

2026-07-28 14:38:12,085 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:13,050 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:13,051 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:13,170 - BERTopic - Cluster - Completed ✓

BERTopic inference: 112,000/346,772

2026-07-28 14:38:17,049 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:18,146 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:18,147 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:18,232 - BERTopic - Cluster - Completed ✓

BERTopic inference: 114,000/346,772

2026-07-28 14:38:21,247 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:22,134 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:22,135 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:22,215 - BERTopic - Cluster - Completed ✓

BERTopic inference: 116,000/346,772

2026-07-28 14:38:25,265 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:26,166 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:26,167 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:26,244 - BERTopic - Cluster - Completed ✓

BERTopic inference: 118,000/346,772

2026-07-28 14:38:29,715 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:31,044 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:31,045 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:31,172 - BERTopic - Cluster - Completed ✓

BERTopic inference: 120,000/346,772

2026-07-28 14:38:34,596 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:35,563 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:35,564 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:35,643 - BERTopic - Cluster - Completed ✓

BERTopic inference: 122,000/346,772

2026-07-28 14:38:38,662 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:39,581 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:39,582 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:39,658 - BERTopic - Cluster - Completed ✓

BERTopic inference: 124,000/346,772

2026-07-28 14:38:42,851 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:44,143 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:44,144 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:44,272 - BERTopic - Cluster - Completed ✓

BERTopic inference: 126,000/346,772

2026-07-28 14:38:47,757 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:48,654 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:48,655 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:48,737 - BERTopic - Cluster - Completed ✓

BERTopic inference: 128,000/346,772

2026-07-28 14:38:51,680 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:52,575 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:52,576 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:52,674 - BERTopic - Cluster - Completed ✓

BERTopic inference: 130,000/346,772

2026-07-28 14:38:55,723 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:38:56,698 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:38:56,699 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:38:56,824 - BERTopic - Cluster - Completed ✓

BERTopic inference: 132,000/346,772

2026-07-28 14:39:00,553 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:01,592 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:01,593 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:01,669 - BERTopic - Cluster - Completed ✓

BERTopic inference: 134,000/346,772

2026-07-28 14:39:04,768 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:05,690 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:05,691 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:05,767 - BERTopic - Cluster - Completed ✓

BERTopic inference: 136,000/346,772

2026-07-28 14:39:08,791 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:09,747 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:09,748 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:09,825 - BERTopic - Cluster - Completed ✓

BERTopic inference: 138,000/346,772

2026-07-28 14:39:13,189 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:14,454 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:14,456 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:14,587 - BERTopic - Cluster - Completed ✓

BERTopic inference: 140,000/346,772

2026-07-28 14:39:17,843 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:18,783 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:18,784 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:18,860 - BERTopic - Cluster - Completed ✓

BERTopic inference: 142,000/346,772

2026-07-28 14:39:21,977 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:22,962 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:22,964 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:23,050 - BERTopic - Cluster - Completed ✓

BERTopic inference: 144,000/346,772

2026-07-28 14:39:26,265 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:27,557 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:27,559 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:27,677 - BERTopic - Cluster - Completed ✓

BERTopic inference: 146,000/346,772

2026-07-28 14:39:31,228 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:32,224 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:32,225 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:32,298 - BERTopic - Cluster - Completed ✓

BERTopic inference: 148,000/346,772

2026-07-28 14:39:35,374 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:36,299 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:36,300 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:36,372 - BERTopic - Cluster - Completed ✓

BERTopic inference: 150,000/346,772

2026-07-28 14:39:39,329 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:40,360 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:40,361 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:40,474 - BERTopic - Cluster - Completed ✓

BERTopic inference: 152,000/346,772

2026-07-28 14:39:44,344 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:45,275 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:45,276 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:45,355 - BERTopic - Cluster - Completed ✓

BERTopic inference: 154,000/346,772

2026-07-28 14:39:48,352 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:49,290 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:49,291 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:49,367 - BERTopic - Cluster - Completed ✓

BERTopic inference: 156,000/346,772

2026-07-28 14:39:52,346 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:53,328 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:53,329 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:53,408 - BERTopic - Cluster - Completed ✓

BERTopic inference: 158,000/346,772

2026-07-28 14:39:57,029 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:39:58,355 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:39:58,357 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:39:58,492 - BERTopic - Cluster - Completed ✓

BERTopic inference: 160,000/346,772

2026-07-28 14:40:01,655 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:02,594 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:02,594 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:02,670 - BERTopic - Cluster - Completed ✓

BERTopic inference: 162,000/346,772

2026-07-28 14:40:05,655 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:06,612 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:06,613 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:06,689 - BERTopic - Cluster - Completed ✓

BERTopic inference: 164,000/346,772

2026-07-28 14:40:10,030 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:11,332 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:11,334 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:11,449 - BERTopic - Cluster - Completed ✓

BERTopic inference: 166,000/346,772

2026-07-28 14:40:14,997 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:16,028 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:16,029 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:16,104 - BERTopic - Cluster - Completed ✓

BERTopic inference: 168,000/346,772

2026-07-28 14:40:19,247 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:20,169 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:20,170 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:20,247 - BERTopic - Cluster - Completed ✓

BERTopic inference: 170,000/346,772

2026-07-28 14:40:23,444 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:24,715 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:24,716 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:24,834 - BERTopic - Cluster - Completed ✓

BERTopic inference: 172,000/346,772

2026-07-28 14:40:28,358 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:29,268 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:29,269 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:29,344 - BERTopic - Cluster - Completed ✓

BERTopic inference: 174,000/346,772

2026-07-28 14:40:32,563 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:33,510 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:33,511 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:33,591 - BERTopic - Cluster - Completed ✓

BERTopic inference: 176,000/346,772

2026-07-28 14:40:36,630 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:37,604 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:37,606 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:37,728 - BERTopic - Cluster - Completed ✓

BERTopic inference: 178,000/346,772

2026-07-28 14:40:41,644 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:42,622 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:42,623 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:42,699 - BERTopic - Cluster - Completed ✓

BERTopic inference: 180,000/346,772

2026-07-28 14:40:45,758 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:46,723 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:46,724 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:46,798 - BERTopic - Cluster - Completed ✓

BERTopic inference: 182,000/346,772

2026-07-28 14:40:49,822 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:50,751 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:50,752 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:50,824 - BERTopic - Cluster - Completed ✓

BERTopic inference: 184,000/346,772

2026-07-28 14:40:54,363 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:40:55,690 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:40:55,691 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:40:55,843 - BERTopic - Cluster - Completed ✓

BERTopic inference: 186,000/346,772

2026-07-28 14:40:59,161 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:00,084 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:00,085 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:00,175 - BERTopic - Cluster - Completed ✓

BERTopic inference: 188,000/346,772

2026-07-28 14:41:03,211 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:04,156 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:04,157 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:04,241 - BERTopic - Cluster - Completed ✓

BERTopic inference: 190,000/346,772

2026-07-28 14:41:07,622 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:08,897 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:08,899 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:09,024 - BERTopic - Cluster - Completed ✓

BERTopic inference: 192,000/346,772

2026-07-28 14:41:12,550 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:13,442 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:13,443 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:13,521 - BERTopic - Cluster - Completed ✓

BERTopic inference: 194,000/346,772

2026-07-28 14:41:16,610 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:17,604 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:17,605 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:17,679 - BERTopic - Cluster - Completed ✓

BERTopic inference: 196,000/346,772

2026-07-28 14:41:20,777 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:22,043 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:22,045 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:22,156 - BERTopic - Cluster - Completed ✓

BERTopic inference: 198,000/346,772

2026-07-28 14:41:25,860 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:26,786 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:26,787 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:26,863 - BERTopic - Cluster - Completed ✓

BERTopic inference: 200,000/346,772

2026-07-28 14:41:30,170 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:31,125 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:31,126 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:31,211 - BERTopic - Cluster - Completed ✓

BERTopic inference: 202,000/346,772

2026-07-28 14:41:34,390 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:35,386 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:35,388 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:35,507 - BERTopic - Cluster - Completed ✓

BERTopic inference: 204,000/346,772

2026-07-28 14:41:39,478 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:40,397 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:40,398 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:40,476 - BERTopic - Cluster - Completed ✓

BERTopic inference: 206,000/346,772

2026-07-28 14:41:43,569 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:44,501 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:44,502 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:44,577 - BERTopic - Cluster - Completed ✓

BERTopic inference: 208,000/346,772

2026-07-28 14:41:47,738 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:48,656 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:48,657 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:48,732 - BERTopic - Cluster - Completed ✓

BERTopic inference: 210,000/346,772

2026-07-28 14:41:52,571 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:53,909 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:53,911 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:53,999 - BERTopic - Cluster - Completed ✓

BERTopic inference: 212,000/346,772

2026-07-28 14:41:57,187 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:41:58,140 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:41:58,141 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:41:58,223 - BERTopic - Cluster - Completed ✓

BERTopic inference: 214,000/346,772

2026-07-28 14:42:01,519 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:02,438 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:02,439 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:02,529 - BERTopic - Cluster - Completed ✓

BERTopic inference: 216,000/346,772

2026-07-28 14:42:05,932 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:07,240 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:07,242 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:07,370 - BERTopic - Cluster - Completed ✓

BERTopic inference: 218,000/346,772

2026-07-28 14:42:10,740 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:11,716 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:11,717 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:11,796 - BERTopic - Cluster - Completed ✓

BERTopic inference: 220,000/346,772

2026-07-28 14:42:14,929 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:15,865 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:15,866 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:15,951 - BERTopic - Cluster - Completed ✓

BERTopic inference: 222,000/346,772

2026-07-28 14:42:19,336 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:20,588 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:20,589 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:20,706 - BERTopic - Cluster - Completed ✓

BERTopic inference: 224,000/346,772

2026-07-28 14:42:24,284 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:25,250 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:25,251 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:25,329 - BERTopic - Cluster - Completed ✓

BERTopic inference: 226,000/346,772

2026-07-28 14:42:29,307 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:30,205 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:30,206 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:30,279 - BERTopic - Cluster - Completed ✓

BERTopic inference: 228,000/346,772

2026-07-28 14:42:33,543 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:34,770 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:34,770 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:34,888 - BERTopic - Cluster - Completed ✓

BERTopic inference: 230,000/346,772

2026-07-28 14:42:38,427 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:39,289 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:39,292 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:39,366 - BERTopic - Cluster - Completed ✓

BERTopic inference: 232,000/346,772

2026-07-28 14:42:42,462 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:43,349 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:43,350 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:43,444 - BERTopic - Cluster - Completed ✓

BERTopic inference: 234,000/346,772

2026-07-28 14:42:46,548 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:47,567 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:47,568 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:47,690 - BERTopic - Cluster - Completed ✓

BERTopic inference: 236,000/346,772

2026-07-28 14:42:51,540 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:52,423 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:52,424 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:52,512 - BERTopic - Cluster - Completed ✓

BERTopic inference: 238,000/346,772

2026-07-28 14:42:55,629 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:42:56,522 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:42:56,523 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:42:56,601 - BERTopic - Cluster - Completed ✓

BERTopic inference: 240,000/346,772

2026-07-28 14:42:59,753 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:00,656 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:00,657 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:00,728 - BERTopic - Cluster - Completed ✓

BERTopic inference: 242,000/346,772

2026-07-28 14:43:04,320 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:05,582 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:05,583 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:05,655 - BERTopic - Cluster - Completed ✓

BERTopic inference: 244,000/346,772

2026-07-28 14:43:08,714 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:09,638 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:09,639 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:09,730 - BERTopic - Cluster - Completed ✓

BERTopic inference: 246,000/346,772

2026-07-28 14:43:12,827 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:13,803 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:13,804 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:13,890 - BERTopic - Cluster - Completed ✓

BERTopic inference: 248,000/346,772

2026-07-28 14:43:17,388 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:18,632 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:18,634 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:18,751 - BERTopic - Cluster - Completed ✓

BERTopic inference: 250,000/346,772

2026-07-28 14:43:22,074 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:22,996 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:22,997 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:23,074 - BERTopic - Cluster - Completed ✓

BERTopic inference: 252,000/346,772

2026-07-28 14:43:26,182 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:27,075 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:27,076 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:27,148 - BERTopic - Cluster - Completed ✓

BERTopic inference: 254,000/346,772

2026-07-28 14:43:30,279 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:31,561 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:31,563 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:31,725 - BERTopic - Cluster - Completed ✓

BERTopic inference: 256,000/346,772

2026-07-28 14:43:35,345 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:36,229 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:36,230 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:36,300 - BERTopic - Cluster - Completed ✓

BERTopic inference: 258,000/346,772

2026-07-28 14:43:39,434 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:40,324 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:40,325 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:40,397 - BERTopic - Cluster - Completed ✓

BERTopic inference: 260,000/346,772

2026-07-28 14:43:43,557 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:44,662 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:44,663 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:44,785 - BERTopic - Cluster - Completed ✓

BERTopic inference: 262,000/346,772

2026-07-28 14:43:48,527 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:49,419 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:49,420 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:49,494 - BERTopic - Cluster - Completed ✓

BERTopic inference: 264,000/346,772

2026-07-28 14:43:52,572 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:53,469 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:53,470 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:53,544 - BERTopic - Cluster - Completed ✓

BERTopic inference: 266,000/346,772

2026-07-28 14:43:56,698 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:43:57,667 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:43:57,668 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:43:57,761 - BERTopic - Cluster - Completed ✓

BERTopic inference: 268,000/346,772

2026-07-28 14:44:01,514 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:02,713 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:02,714 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:02,787 - BERTopic - Cluster - Completed ✓

BERTopic inference: 270,000/346,772

2026-07-28 14:44:05,919 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:06,795 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:06,798 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:06,868 - BERTopic - Cluster - Completed ✓

BERTopic inference: 272,000/346,772

2026-07-28 14:44:09,852 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:10,730 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:10,731 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:10,802 - BERTopic - Cluster - Completed ✓

BERTopic inference: 274,000/346,772

2026-07-28 14:44:14,173 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:15,354 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:15,356 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:15,472 - BERTopic - Cluster - Completed ✓

BERTopic inference: 276,000/346,772

2026-07-28 14:44:18,935 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:19,837 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:19,838 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:19,912 - BERTopic - Cluster - Completed ✓

BERTopic inference: 278,000/346,772

2026-07-28 14:44:23,027 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:23,967 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:23,969 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:24,048 - BERTopic - Cluster - Completed ✓

BERTopic inference: 280,000/346,772

2026-07-28 14:44:27,359 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:28,644 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:28,646 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:28,780 - BERTopic - Cluster - Completed ✓

BERTopic inference: 282,000/346,772

2026-07-28 14:44:32,490 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:33,411 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:33,412 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:33,499 - BERTopic - Cluster - Completed ✓

BERTopic inference: 284,000/346,772

2026-07-28 14:44:36,726 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:37,615 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:37,616 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:37,688 - BERTopic - Cluster - Completed ✓

BERTopic inference: 286,000/346,772

2026-07-28 14:44:40,835 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:42,013 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:42,014 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:42,132 - BERTopic - Cluster - Completed ✓

BERTopic inference: 288,000/346,772

2026-07-28 14:44:45,906 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:46,877 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:46,878 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:46,952 - BERTopic - Cluster - Completed ✓

BERTopic inference: 290,000/346,772

2026-07-28 14:44:50,167 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:51,017 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:51,017 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:51,089 - BERTopic - Cluster - Completed ✓

BERTopic inference: 292,000/346,772

2026-07-28 14:44:54,259 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:44:55,113 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:44:55,113 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:44:55,193 - BERTopic - Cluster - Completed ✓

BERTopic inference: 294,000/346,772

2026-07-28 14:44:58,987 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:00,113 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:00,114 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:00,187 - BERTopic - Cluster - Completed ✓

BERTopic inference: 296,000/346,772

2026-07-28 14:45:03,450 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:04,325 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:04,325 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:04,399 - BERTopic - Cluster - Completed ✓

BERTopic inference: 298,000/346,772

2026-07-28 14:45:07,575 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:08,477 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:08,478 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:08,549 - BERTopic - Cluster - Completed ✓

BERTopic inference: 300,000/346,772

2026-07-28 14:45:12,096 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:13,322 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:13,324 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:13,438 - BERTopic - Cluster - Completed ✓

BERTopic inference: 302,000/346,772

2026-07-28 14:45:16,603 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:17,476 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:17,477 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:17,548 - BERTopic - Cluster - Completed ✓

BERTopic inference: 304,000/346,772

2026-07-28 14:45:20,736 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:21,621 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:21,622 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:21,700 - BERTopic - Cluster - Completed ✓

BERTopic inference: 306,000/346,772

2026-07-28 14:45:25,027 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:26,221 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:26,223 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:26,339 - BERTopic - Cluster - Completed ✓

BERTopic inference: 308,000/346,772

2026-07-28 14:45:29,851 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:30,737 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:30,738 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:30,813 - BERTopic - Cluster - Completed ✓

BERTopic inference: 310,000/346,772

2026-07-28 14:45:33,926 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:34,805 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:34,806 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:34,880 - BERTopic - Cluster - Completed ✓

BERTopic inference: 312,000/346,772

2026-07-28 14:45:38,021 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:39,193 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:39,196 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:39,333 - BERTopic - Cluster - Completed ✓

BERTopic inference: 314,000/346,772

2026-07-28 14:45:43,021 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:43,921 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:43,922 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:43,992 - BERTopic - Cluster - Completed ✓

BERTopic inference: 316,000/346,772

2026-07-28 14:45:47,217 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:48,141 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:48,142 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:48,218 - BERTopic - Cluster - Completed ✓

BERTopic inference: 318,000/346,772

2026-07-28 14:45:51,369 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:52,240 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:52,241 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:52,315 - BERTopic - Cluster - Completed ✓

BERTopic inference: 320,000/346,772

2026-07-28 14:45:56,028 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:45:57,221 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:45:57,222 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:45:57,296 - BERTopic - Cluster - Completed ✓

BERTopic inference: 322,000/346,772

2026-07-28 14:46:00,552 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:01,409 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:01,410 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:01,490 - BERTopic - Cluster - Completed ✓

BERTopic inference: 324,000/346,772

2026-07-28 14:46:04,641 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:05,502 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:05,503 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:05,575 - BERTopic - Cluster - Completed ✓

BERTopic inference: 326,000/346,772

2026-07-28 14:46:09,021 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:10,260 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:10,262 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:10,371 - BERTopic - Cluster - Completed ✓

BERTopic inference: 328,000/346,772

2026-07-28 14:46:13,691 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:14,616 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:14,617 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:14,697 - BERTopic - Cluster - Completed ✓

BERTopic inference: 330,000/346,772

2026-07-28 14:46:17,807 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:18,723 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:18,724 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:18,795 - BERTopic - Cluster - Completed ✓

BERTopic inference: 332,000/346,772

2026-07-28 14:46:22,212 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:23,442 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:23,444 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:23,555 - BERTopic - Cluster - Completed ✓

BERTopic inference: 334,000/346,772

2026-07-28 14:46:26,952 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:27,863 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:27,864 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:27,937 - BERTopic - Cluster - Completed ✓

BERTopic inference: 336,000/346,772

2026-07-28 14:46:31,148 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:32,071 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:32,072 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:32,175 - BERTopic - Cluster - Completed ✓

BERTopic inference: 338,000/346,772

2026-07-28 14:46:35,329 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:36,548 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:36,549 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:36,672 - BERTopic - Cluster - Completed ✓

BERTopic inference: 340,000/346,772

2026-07-28 14:46:40,491 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:41,383 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:41,384 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:41,466 - BERTopic - Cluster - Completed ✓

BERTopic inference: 342,000/346,772

2026-07-28 14:46:44,701 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:45,741 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:45,742 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:45,820 - BERTopic - Cluster - Completed ✓

BERTopic inference: 344,000/346,772

2026-07-28 14:46:48,914 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:49,819 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:49,820 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:49,946 - BERTopic - Cluster - Completed ✓

BERTopic inference: 346,000/346,772

2026-07-28 14:46:51,531 - BERTopic - Dimensionality - Reducing dimensionality of input embeddings.
2026-07-28 14:46:52,004 - BERTopic - Dimensionality - Completed ✓
2026-07-28 14:46:52,006 - BERTopic - Clustering - Approximating new points with `hdbscan_model`
2026-07-28 14:46:52,049 - BERTopic - Cluster - Completed ✓

BERTopic inference: 346,772/346,772
Saved review assignments: /content/drive/MyDrive/yelp_topic_modeling/review_topic_assignments.parquet
Saved business topics:     /content/drive/MyDrive/yelp_topic_modeling/business_top_topics.csv

,business_id,business_name,topic_id,topic_label,topic_review_count,average_topic_score,business_assigned_reviews,topic_share,topic_rank,model
0,tZnPqmwGcLjYeBdwyvhazg,'O' Bar + Kitchen,3,"wine, tasting, wines, bar, tour",8,0.933225,11,0.727273,1,BERTopic
1,tZnPqmwGcLjYeBdwyvhazg,'O' Bar + Kitchen,2,"tacos, food, sandwich, chicken, taco",3,0.705908,11,0.272727,2,BERTopic
2,BZAVgg5ybeX_a4w-FW0mbA,1-800-GOT-JUNK? Central Coast,0,"car, store, customer, said, business",18,0.863037,18,1.000000,1,BERTopic
3,JYhsqscSETHckYeqjGZ5Yg,1-800-GOT-JUNK? Santa Barbara,0,"car, store, customer, said, business",14,0.915802,14,1.000000,1,BERTopic
4,LsniEK_m_Jbj7JMbT4eRxQ,101 Deli,2,"tacos, food, sandwich, chicken, taco",5,0.848800,6,0.833333,1,BERTopic
5,LsniEK_m_Jbj7JMbT4eRxQ,101 Deli,13,"thai, food, chinese, noodles, chicken",1,0.655181,6,0.166667,2,BERTopic
6,hwdWsUws6m2vrvfFz5TjQg,101 Property Mgmt,0,"car, store, customer, said, business",8,0.825245,8,1.000000,1,BERTopic
7,2l-spLLGUzRiZg8dF623Nw,1114 Sports Bar & Games,2,"tacos, food, sandwich, chicken, taco",7,0.798412,22,0.318182,1,BERTopic
8,2l-spLLGUzRiZg8dF623Nw,1114 Sports Bar & Games,3,"wine, tasting, wines, bar, tour",6,0.822234,22,0.272727,2,BERTopic
9,2l-spLLGUzRiZg8dF623Nw,1114 Sports Bar & Games,16,"pizza, crust, pizzas, pizza good, ordered",5,0.603039,22,0.227273,3,BERTopic
10,2l-spLLGUzRiZg8dF623Nw,1114 Sports Bar & Games,0,"car, store, customer, said, business",3,0.880077,22,0.136364,4,BERTopic
11,2l-spLLGUzRiZg8dF623Nw,1114 Sports Bar & Games,6,"wedding, event, venue, planning, guests",1,0.678485,22,0.045455,5,BERTopic
12,ZOfi2iKhamGdEK-iC5dLuw,1329 Salon and Spa,5,"hair, cut, salon, haircut, stylist",70,0.806426,79,0.886076,1,BERTopic
13,ZOfi2iKhamGdEK-iC5dLuw,1329 Salon and Spa,11,"massage, massages, spa, body, relax",5,0.604540,79,0.063291,2,BERTopic
14,ZOfi2iKhamGdEK-iC5dLuw,1329 Salon and Spa,0,"car, store, customer, said, business",1,0.912016,79,0.012658,3,BERTopic
15,ZOfi2iKhamGdEK-iC5dLuw,1329 Salon and Spa,14,"nails, nail, mani, pedi, mani pedi",1,0.164709,79,0.012658,4,BERTopic
16,ZOfi2iKhamGdEK-iC5dLuw,1329 Salon and Spa,18,"wax, waxing, brazilian, eyebrows, salon",1,0.447036,79,0.012658,5,BERTopic
17,x6ByESFVanIYcomQsXQYGw,19 Blue Salon,5,"hair, cut, salon, haircut, stylist",96,0.740838,102,0.941176,1,BERTopic
18,x6ByESFVanIYcomQsXQYGw,19 Blue Salon,19,"makeup, hair, wedding, hair makeup, emily",3,1.000000,102,0.029412,2,BERTopic
19,x6ByESFVanIYcomQsXQYGw,19 Blue Salon,18,"wax, waxing, brazilian, eyebrows, salon",2,0.702184,102,0.019608,3,BERTopic